language: python
# python versions to use during the tests
python:
    - "3.4"
# command to install dependencies
install:
    - pip install -r requirements.txt
# command to run tests
script:
    - py.test --cov-report term-missing --cov=dockerviolations
    - py.test --doctest-modules --cov=dockerviolations --cov-report term-missing
#    - py.test
branches:
  only:
   - master
after_success:
    - coveralls
notifications:
  email:
    recipients:
      - dheeruymv@gmail.com
    on_success: always
    on_failure: always